Feature tables
DLUT-SIE/TMSFTT-FE pull request #178
Opened 2019-04-29 15:54 UTC by Spground

2019-04-30 05:47 UTC, Time1ess requested changes

2019-04-30 05:47 UTC, Time1ess commented on src/app/admin/modules/data-management/components/table-export/table-export.component.ts
> +                console.log(error);
Remove `console.log`

2019-04-30 05:47 UTC, Time1ess commented on src/app/shared/services/logger.service.spec.ts
> +        if (!environment.production) {
In these unit tests, `environment.production` would never be `true`, so the if condition is unnecessary. But this way you can't test whether there will be logs in when `environment.production` is `true`, consider adding mocks to test this service in a production mode.

2019-04-30 05:47 UTC, Time1ess commented on src/environments/environment.interface.ts
> +  HOST: string;
What's this property for? Please add comments.

2019-04-30 06:21 UTC, Spground commented on src/app/shared/services/logger.service.spec.ts
> +        if (!environment.production) {
[https://stackoverflow.com/questions/49091393/how-to-mock-environment-files-import-in-unit-tests](url)
貌似`enviroment.ts`不能被mock，所以这里考虑使用一个`enviroment service`来抽象`enviroment.ts`，同时也能方面后期的单测的mock，so any suggestions about this?

2019-04-30 09:42 UTC, Time1ess commented on src/app/shared/services/logger.service.spec.ts
> +        if (!environment.production) {
An `EnvironmentService` LGTM.

2019-05-01 05:08 UTC, Time1ess approved these changes

2019-05-01 05:08 UTC, Time1ess commented on src/environments/environment.interface.ts
> +  HOST: string;
I mean it seems that there is no need to keep this field anymore.

2019-05-01 05:08 UTC, Time1ess commented on src/app/shared/services/environment.service.ts
> +export class EnvironmentService {
If `EnvironmentService` has no need to add tests, you might need to exclude it from coverage report by adding it in the `codeCoverageExclude` section in `angular.json`.

2019-05-01 11:43 UTC, merged