Complete List View and List Details
DLUT-SIE/TMSFTT-FE pull request #40
Opened 2019-02-28 02:54 UTC by dutlzn

Review List View and List Details.

2019-03-01 01:33 UTC, Time1ess requested changes

2019-03-01 01:33 UTC, Time1ess commented on src/app/components/sidebar/sidebar.component.ts
> +    { path: '/training-event/table-list', title: '校内培训活动查看', icon: 'create', class: '' },
In order to be consistent, I personally prefer '/training-event/events', this way the URL will be similar to backend APIs.

2019-03-01 01:33 UTC, Time1ess commented on src/app/interfaces/event.ts
> +  program: number;
I think it's better to return program as an object as an extra field. For example, you can return the ID of the program as it is, and add another field on CampusEventSerializer, named `program_detail`, and this field serialize the program which the event is related to. In this way, we can display human-friendly information about the program in user's browser.

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/components/table-list/table-list.component.html
> +                <th class="col-2 col-sm-1"></th>
I think we need to display `name`, `time`, `location`, `num_hours` and `num_participants` here. Besides, an `ID` means nothing to our users who don't know our business logic, so please remove it. And please make sure that the number of `<td>` in `<tbody>` matches the number of `<th>` in `<thead>`.

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/components/table-list/table-list.component.spec.ts
> +          provide: HAMMER_LOADER,
Why are you providing `HAMMER_LOADER` here?

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/components/table-list/table-list.component.ts
> +export class TableListComponent implements OnInit {
This is a bad name considering that the name is general and not related to specific model. We can discuss whether it's appropriate to use a general component to display list of instances for all models, but here let's name it as `CampusEventListComponent`.

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.ts
> + /** How often should we query latest notifications. */
This comment is copied and  includes `notifications`, please fix it.

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.ts
> + private REFRESH_INTERVAL = 30 * 1000;
I doubt that this auto-reload feature is required in your case. Normally, we don't need the list to be refreshed if no input is performed by user.

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.ts
> + getEvent(id: number) {
Please comment this function, and I think it's better to name it as `getCampusEvent` instead of `getEvent`.

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.ts
> + getEvents(offset?: number, limit?: number) {
Comment please. (And update the name)

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/components/table-list/table-list.component.ts
> +  pageSize = 5;
Pagination size should have been defined in `environment.ts`, do not use custom value if not necessary.

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.spec.ts
> +  const dummyEvent: CampusEventResponse = {
You don't need real data in these tests, consider replace them with `req.flush({count: 2});`

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.spec.ts
> +  const authenticationSucceed$ = new Subject<void>();
As per #23 , please declare `authenticationSucceed`  here and define it later in beforeEach, to avoid memory leak.

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/training-event-routing.module.ts
> +        path: 'table-list',
Ditto.

2019-03-01 01:33 UTC, Time1ess commented on src/app/modules/training-event/training-event-routing.module.ts
> +            component: TableListComponent,
Ditto.

2019-03-04 01:01 UTC, Time1ess commented
The branch is out-dated, please update the branch.

2019-03-04 02:28 UTC, Time1ess requested changes
PLEASE review your code before submitting!

2019-03-04 02:28 UTC, Time1ess commented on src/app/app.module.ts
> +// import { CampusEventListComponent } from './modules/training-event/components/campus-event-list/campus-event-list.component';
Why are you keeping this line?

2019-03-04 02:28 UTC, Time1ess commented on src/app/app.module.ts
> +import { UserProfileComponent } from 'src/app/demo/user-profile/user-profile.component';
Pls keep the space as it is, these demo components will be removed, a space is preferred to separate them from other imports.

2019-03-04 02:28 UTC, Time1ess commented on src/app/interfaces/event.ts
> +  // program: number;
Could you describe the reason why you are commenting the `program` field? And I believe `program_detail` should be other interfaces (Maybe a `Program` interface) instead of `string`.

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/components/campus-event-list/campus-event-list.component.html
> +                  <td class="col-6 col-sm-2 text-justify">{{ item.name}}</td>
Pls keep your spaces symmetric, you have a space after `{{`, but no space before `}}`.

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/components/campus-event-list/campus-event-list.component.spec.ts
> +    program_detail: '计算机',
Ditto.

2019-03-04 02:28 UTC, Time1ess commented on src/app/interfaces/event.ts
> +  create_time: string;
Pls read the code carefully, some of these fields are inherited from its parent interface, there is no need to declare them multiple times.

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/components/campus-event-list/campus-event-list.component.html
> +                  <td class="col-6 col-sm-2">{{ item.num_hours|number:"0.1-1"}} </td>
Spaces around `|` is preferred.

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/components/campus-event-list/campus-event-list.component.spec.ts
> +            getEvents,
There is no need to use spy, just use:
```
useValue: {
  getEvents: () => getEvents$,
}
```

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/components/campus-event-list/campus-event-list.component.ts
> +  displayedColumns: string[] = ['id', 'name', 'location'];
You're not using `MatTable`, remove this line.

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/components/campus-event-list/campus-event-list.component.ts
> +export class CampusEventListComponent implements OnInit {
Pls provide useful comment for the component to describe the use.

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/components/campus-event-list/campus-event-list.component.ts
> +  constructor(
Add a blank line.

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.spec.ts
> +    service.getEvents().subscribe(
If you are not using `data`, just use: `.subscribe()`

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.ts
> +import { Injectable} from '@angular/core';
Space

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.ts
> +  getEvent(id: number) {
The indentation is strange.

2019-03-04 02:28 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.ts
> +   offset = 0;
Do you think this is right?

2019-03-08 09:30 UTC, Time1ess commented
@dutlzn The branch is out-dated and conflicts with dev branch.

2019-03-12 01:25 UTC, a8520238 submitted a review, later dismissed

2019-03-12 01:28 UTC, dutlzn commented
![image](https://user-images.githubusercontent.com/45323439/54168374-1e4c7600-44a9-11e9-8ae0-d8bad2e7d21b.png)

2019-03-15 01:55 UTC, Time1ess requested changes

2019-03-15 01:55 UTC, Time1ess commented on src/app/interfaces/event.ts
> +  program: number;
program_detail should be a `Program` object, not `object`.

2019-03-15 01:55 UTC, Time1ess commented on src/app/modules/training-event/components/campus-event-list/campus-event-list.component.html
> +                <th class="col-6 col-sm-2">名字</th>
The sum of `col-*` should be `12`

2019-03-15 01:55 UTC, Time1ess commented on src/app/modules/training-event/components/campus-event-list/campus-event-list.component.ts
> +export class CampusEventListComponent implements OnInit {
Move comment above.

2019-03-15 01:55 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.ts
> +    private readonly http: HttpClient) {}
Do not edit this line.

2019-03-15 02:52 UTC, Time1ess requested changes

2019-03-15 02:52 UTC, Time1ess commented on src/app/modules/training-event/services/event.service.ts
> +    private readonly http: HttpClient
A comma is required.

2019-03-15 03:01 UTC, Time1ess approved these changes

2019-03-15 03:05 UTC, a8520238 approved these changes

2019-03-15 03:09 UTC, Yqzzxlj approved these changes

2019-03-15 03:09 UTC, merged