Lgz training program
DLUT-SIE/TMSFTT-FE pull request #43
Opened 2019-03-04 12:15 UTC by a8520238

我增加了programs组件

2019-03-04 12:42 UTC, a8520238 reviewed
some lint programs

2019-03-05 05:36 UTC, Time1ess requested changes
Revert changes on package-lock.json.

2019-03-05 05:36 UTC, Time1ess commented on src/app/components/sidebar/sidebar.component.ts
> +    { path: '/training-program/programs', title: '培训项目', icon: 'create', class: '' },
`title` should be '培训项目查看'

2019-03-05 05:36 UTC, Time1ess commented on src/app/interfaces/department.ts
> +    admins: [];
The type of `admins` should be `number[]`

2019-03-05 05:36 UTC, Time1ess commented on src/app/interfaces/department.ts
> +    up_time: string;
Wrong name.

2019-03-05 05:36 UTC, Time1ess commented on src/app/interfaces/category.ts
> +export interface Category {
Name should be consistent with backend.

2019-03-05 05:36 UTC, Time1ess commented on src/app/interfaces/program.ts
> +export interface ProgramDetail {
Wrong name.

2019-03-05 05:36 UTC, Time1ess commented on src/app/interfaces/program.ts
> +    form: [];
Type.

2019-03-05 05:36 UTC, Time1ess commented on src/app/modules/training-program/components/programs/programs.component.html
> +                <th class="col-2 col-sm-1"></th>
The sum of col sizes should no more than 12.

2019-03-05 05:36 UTC, Time1ess commented on src/app/modules/training-program/components/programs/programs.component.ts
> +  displayedColumns: string[] = ['name', 'department'];
You are not using `MatTable`, the `displayedColumns` isn't needed.

2019-03-05 05:36 UTC, Time1ess commented on src/app/modules/training-program/services/program.service.ts
> +  /** How often should we query latest programforms. */
Delete comment.

2019-03-05 05:36 UTC, Time1ess commented on src/app/modules/training-program/services/program.service.ts
> +    this.authService.authenticationSucceed.subscribe(() => {
Why do you need this line?

2019-03-05 10:33 UTC, Time1ess requested changes

2019-03-05 10:33 UTC, Time1ess commented on src/app/modules/training-program/components/programs/programs.component.html
>                  <th class="col-2 col-sm-1"></th>
The error isn't fixed.

2019-03-05 11:01 UTC, a8520238 commented
我已经修复了column问题
![image](https://user-images.githubusercontent.com/44317801/53801049-1f494900-3f79-11e9-89da-b515d4a7b003.png)
效果如上

2019-03-05 11:04 UTC, Time1ess commented
1. Normally, we would make sure that the sum of column sizes are equal to 12, please update.
2. You haven't revert the changes on `package-lock.json`.

2019-03-05 12:50 UTC, a8520238 commented
现在我回退了版本，并更改了之前的错误
![image](https://user-images.githubusercontent.com/44317801/53806561-39d6ee80-3f88-11e9-9d5c-aeb58a4acf35.png)
页面如上

2019-03-06 01:30 UTC, a8520238 commented
修改命名

2019-03-06 02:01 UTC, a8520238 commented
修改类型和排版

2019-03-06 02:24 UTC, a8520238 commented
类型修改

2019-03-08 08:52 UTC, dutlzn submitted a review, later dismissed

2019-03-08 09:29 UTC, Time1ess commented
@a8520238 The branch is out-dated.

2019-03-12 07:53 UTC, Time1ess requested changes

2019-03-12 07:53 UTC, Time1ess commented on src/app/modules/training-program/components/programs/programs.component.ts
> +  pageSize = 5;
Use global constant instead of 5.

2019-03-14 01:41 UTC, Time1ess approved these changes

2019-03-14 03:14 UTC, dutlzn approved these changes

2019-03-14 03:15 UTC, Yqzzxlj approved these changes

2019-03-14 03:21 UTC, merged