Lzn/event detail
DLUT-SIE/TMSFTT-FE pull request #55
Opened 2019-03-18 05:36 UTC by dutlzn

完成了校内活动详情功能

2019-03-18 05:37 UTC, dutlzn commented
![image](https://user-images.githubusercontent.com/45323439/54509009-f5cdeb80-4982-11e9-904d-da7a4b28b4f2.png)

2019-03-20 13:31 UTC, Yqzzxlj submitted a review, later dismissed

2019-03-30 11:18 UTC, dutlzn commented
![image](https://user-images.githubusercontent.com/45323439/55275406-83fd8680-5320-11e9-92eb-e3729537139a.png)
![image](https://user-images.githubusercontent.com/45323439/55275412-94adfc80-5320-11e9-9a24-316bb28bf86c.png)

2019-03-30 11:29 UTC, ghh82058 requested changes

2019-03-30 11:29 UTC, ghh82058 commented on src/environments/environment.ts
> +  CAS_LOGIN_URL: 'http://10.7.23.250:8000/mock-cas/login/',
These items don't need change.

2019-03-30 11:36 UTC, ghh82058 approved these changes

2019-03-30 11:37 UTC, merged